# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awn < Formula
  desc "awn homebrew test"
  homepage "github.com/rainiring/awn"
  version "0.2.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rainiring/awn/releases/download/v0.2.13/awn_Darwin_x86_64.tar.gz"
      sha256 "5536b792008cc2815f4296d7624080f55ca4dd800074a3f8a9f3a0831c11580f"

      def install
        bin.install "awn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rainiring/awn/releases/download/v0.2.13/awn_Darwin_arm64.tar.gz"
      sha256 "c6f6c20e84d361a5aedac38c8ee43dd2ee9f16685cc3f089e35bc6490c030440"

      def install
        bin.install "awn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rainiring/awn/releases/download/v0.2.13/awn_Linux_x86_64.tar.gz"
        sha256 "b90adbd8e9d70d99f50f481864f68cd3eb96278d926b3aa9132bbeb3ce0eb20d"

        def install
          bin.install "awn"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rainiring/awn/releases/download/v0.2.13/awn_Linux_arm64.tar.gz"
        sha256 "7d7dc1e2717106cba6e7f6cbc30cd34f76522f23eec57184fa07abde1d7fafe9"

        def install
          bin.install "awn"
        end
      end
    end
  end

  test do
    system "#{bin}/awn --version"
  end
end
