# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awn < Formula
  desc "awn homebrew test"
  homepage "github.com/rainiring/awn"
  version "0.2.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rainiring/awn/releases/download/v0.2.8/awn_Darwin_x86_64.tar.gz"
      sha256 "1a688a10647dc727856471fd0bdf2bbe44ddf4efb481b28ada3007174babb8a3"

      def install
        bin.install "awn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rainiring/awn/releases/download/v0.2.8/awn_Darwin_arm64.tar.gz"
      sha256 "86d50c07a538b29be04af26289a1ffaa393e64b4848c08d40bedc6d1bf07739d"

      def install
        bin.install "awn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rainiring/awn/releases/download/v0.2.8/awn_Linux_x86_64.tar.gz"
        sha256 "0ae52e5761c04b2aee4839602de56df193786a6d3f9629a5eb03356988a3cc16"

        def install
          bin.install "awn"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rainiring/awn/releases/download/v0.2.8/awn_Linux_arm64.tar.gz"
        sha256 "ee3135a5b6839e6c5a18520106eee166faae85334b648a6bbdccc0268a5e818d"

        def install
          bin.install "awn"
        end
      end
    end
  end

  test do
    system "#{bin}/awn --version"
  end
end
